### ISSUE TITLE
IPv6 pool natOutgoing doesn't working

### ISSUE THREAD

**Issue by moycat** [tigera/operator#1044]
## Expected Behavior

If I set the `natOutgoing` in the IPv6 pool installation, it should work. The `CALICO_IPV6POOL_NAT_OUTGOING` environment variable of the `calico-node` pods should be set to `true`.

Example installation:

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 100.64.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    - blockSize: 122
      cidr: fc00::/48
      natOutgoing: Enabled
      nodeSelector: all()
```

## Current Behavior

The `calico-node` pods don't have `CALICO_IPV6POOL_NAT_OUTGOING` set, even if `natOutgoing` of the IPv6 pool installation is `Enabled`.

As a result, IPv6 NAT doesn't work. I have to manually edit the `IPPool` configuration to enable it.

## Possible Solution

By default, the NAT Outgoing setting for the IPv6 Pool created at startup is `false` (see [the manual](https://docs.projectcalico.org/archive/v3.17/reference/node/configuration#configuring-the-default-ip-pools)).

However, the operator only sets `CALICO_IPV6POOL_NAT_OUTGOING` to `false` when `NATOutgoing` in an IPv6 pool is disabled. Thus `CALICO_IPV6POOL_NAT_OUTGOING` is either absent or `false`, causing NAT for IPv6 pools never to be enabled.

I've created a PR to fix this (#1038), but the build failed on Semaphore, while the tests all passed on my machine.

## Steps to Reproduce (for bugs)

Apply an IPv6 installation with `natOutgoing` enabled.
