### ISSUE TITLE
Add support for additional labels and annotations to be propagated to all pods

### ISSUE THREAD

**Issue by Chili-Man** [tigera/operator#1099]
We make use of pod labels and annotations to [tag metrics](https://docs.datadoghq.com/agent/kubernetes/tag/?tab=containerizedagent#pod-labels-as-tags) and [configure checks](https://docs.datadoghq.com/agent/kubernetes/integrations/?tab=kubernetes) for pods with DataDog. However, due to the operator managing all of the underlying Kubernetes resources, there is in't a good way to automatically add the labels and configuration during the installation. We would like to see support for passing additional labels and annotations to each of the underlying components that get deployed by this operator, in particular for the `Node`, `Typha`, and `Kubecontrollers`.  

## Expected Behavior

The operator should allow passing user specified custom labels and annotations to the pods  

## Current Behavior

We are currently not able to propogate additional labels or annotations to the operator managed pods. 

## Possible Solution

The `Installation` CRD should have a field like:

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  namespace: management
spec:
    componentLabels:
      - componentName: Node
        podLabels:
            foo: bar

   componentAnnotations:
      - componentName: Typha
        podAnnotations:
          cool: awesome
```

## Steps to Reproduce (for bugs)

N/A

## Context

We would like to add additional labels and annotations to the pods for monitoring and running checks through DataDog 

## Your Environment

* AWS EKS with Amazon Linux 2 nodes

**Comment by tmjd** [comment]
Sorry we missed this request and took so long to respond. This seems like a reasonable request. I'm not sure of the behavior we would want when operator is already setting an annotation or label and the user provided the same one. I'm not sure if one should take precedence or if it should result in reporting degraded in tigerastatus.

Your proposal follows the pattern we started with `componentResources` but I'm not sure I like the pattern we started. I think I like the following better. I'd possibly even consider adding podResources and deprecating `componentResources` in the future.
```
componentMeta:
  - name: Typha
    podAnnotations: ....
    podLabels: ...
```

@caseydavenport WDYT?

I'm not sure of the best way to handle this, does anyone have any good examples of how others handled this? I think I've seen others allow the whole podTemplate be defined but I think we want to keep this operator more opinionated than that, so I don't think that is an option.
