### ISSUE TITLE
Failed to create watcher ListRoot="/calico/ipam/v2/assignment/" error=connection is unauthorized: unknown (get IPAMBlocks.crd.projectcalico.org)

### ISSUE THREAD

**Issue by mad01** [tigera/operator#1294]
calico-kube-controllers is missing rbac with default setup to allow the controller to IPAMBlocks. and keeps returning this logs over and over  

```
2021-05-07 13:37:38.999 [INFO][1] watchercache.go 243: Failed to create watcher ListRoot="/calico/ipam/v2/assignment/" error=connection is unauthorized: unknown (get IPAMBlocks.crd.projectcalico.org) performFullResync=true
2021-05-07 13:37:38.999 [INFO][1] watchercache.go 174: Full resync is required ListRoot="/calico/ipam/v2/assignment/"
```

## Possible Solution

manually adding new cluster role and cluster role binding to service account that runs the service. example patch
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calico-kube-controllers-patch
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - endpoints
  - services
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - crd.projectcalico.org
  resources:
  - ippools
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - crd.projectcalico.org
  resources:
  - blockaffinities
  - ipamblocks
  - ipamhandles
  - networksets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - crd.projectcalico.org
  resources:
  - clusterinformations
  verbs:
  - get
  - create
  - update
- apiGroups:
  - crd.projectcalico.org
  resources:
  - hostendpoints
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - crd.projectcalico.org
  resources:
  - kubecontrollersconfigurations
  verbs:
  - get
  - create
  - update
  - watch
- apiGroups:
  - policy
  resourceNames:
  - calico-kube-controllers
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calico-kube-controllers-patch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calico-kube-controllers-patch
subjects:
- kind: ServiceAccount
  name: calico-kube-controllers
  namespace: calico-system

``` 

## Steps to Reproduce (for bugs)

install using aws cni yaml https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.7/calico.yaml on a 1.18 k8s cluster

## Your Environment
aws eks 1.18
