### ISSUE TITLE
API Server is frequently re-deployed 

### ISSUE THREAD

**Issue by alzabo** [tigera/operator#1776]
The tigera-operator appears to be restarting the calico-apiserver pods every 10 minutes.

## Expected Behavior
Calico API Server does not restart unless a logical change is made.

## Current Behavior
calico-apiserver pods restart approximately every 10 minutes, as shown by the following output from `kubectl get pods -n calico-apiserver -w`

```
$ kubectl get pods -n calico-apiserver -w
NAME                                READY   STATUS    RESTARTS   AGE
calico-apiserver-6f4fbf7b54-d2dd6   1/1     Running   0          4m48s
calico-apiserver-6f4fbf7b54-mwmps   1/1     Running   0          4m48s
calico-apiserver-6f4fbf7b54-v2k2g   1/1     Running   0          4m48s
calico-apiserver-6f4fbf7b54-mwmps   1/1     Terminating   0          10m
calico-apiserver-6f4fbf7b54-d2dd6   1/1     Terminating   0          10m
calico-apiserver-6f4fbf7b54-v2k2g   1/1     Terminating   0          10m
calico-apiserver-6f4fbf7b54-hwsvd   0/1     Pending       0          1s
calico-apiserver-6f4fbf7b54-hwsvd   0/1     Pending       0          1s
calico-apiserver-6f4fbf7b54-cjw9h   0/1     Pending       0          0s
calico-apiserver-6f4fbf7b54-nlgzj   0/1     Pending       0          0s
calico-apiserver-6f4fbf7b54-cjw9h   0/1     Pending       0          0s
calico-apiserver-6f4fbf7b54-nlgzj   0/1     Pending       0          0s
calico-apiserver-6f4fbf7b54-hwsvd   0/1     ContainerCreating   0          1s
calico-apiserver-6f4fbf7b54-cjw9h   0/1     ContainerCreating   0          0s
calico-apiserver-6f4fbf7b54-nlgzj   0/1     ContainerCreating   0          0s
calico-apiserver-6f4fbf7b54-v2k2g   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-d2dd6   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-mwmps   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-d2dd6   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-d2dd6   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-cjw9h   0/1     Running             0          1s
calico-apiserver-6f4fbf7b54-mwmps   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-mwmps   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-nlgzj   0/1     Running             0          1s
calico-apiserver-6f4fbf7b54-hwsvd   0/1     Running             0          3s
calico-apiserver-6f4fbf7b54-v2k2g   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-v2k2g   0/1     Terminating         0          10m
calico-apiserver-6f4fbf7b54-cjw9h   1/1     Running             0          9s
calico-apiserver-6f4fbf7b54-nlgzj   1/1     Running             0          12s
calico-apiserver-6f4fbf7b54-hwsvd   1/1     Running             0          14s
```

When this happens, logs like the following are printed by the tigera-operator pod - The following were all printed in short order at the time when the apiserver deployment was restarted:
```
tigera-operator-648bcdc9cf-67cmw tigera-operator {"level":"info","ts":1644436641.1278439,"logger":"controller_apiserver","msg":"Reconciling APIServer","Request.Namespace":"","Request.Name":"default"}
tigera-operator-648bcdc9cf-67cmw tigera-operator {"level":"info","ts":1644436641.8467112,"logger":"controller_apiserver","msg":"Reconciling APIServer","Request.Namespace":"","Request.Name":"default"}
tigera-operator-648bcdc9cf-67cmw tigera-operator {"level":"info","ts":1644436644.8428574,"logger":"status_manager","msg":"update to tigera status conflicted, retrying","reason":"Operation cannot be fulfilled on tigerastatuses.operator.tigera.io \"apiserver\": the object has been modified; please apply your changes to the latest version and try again"}
tigera-operator-648bcdc9cf-67cmw tigera-operator {"level":"info","ts":1644436649.841111,"logger":"status_manager","msg":"update to tigera status conflicted, retrying","reason":"Operation cannot be fulfilled on tigerastatuses.operator.tigera.io \"apiserver\": the object has been modified; please apply your changes to the latest version and try again"}
tigera-operator-648bcdc9cf-67cmw tigera-operator {"level":"info","ts":1644436659.8435774,"logger":"status_manager","msg":"update to tigera status conflicted, retrying","reason":"Operation cannot be fulfilled on tigerastatuses.operator.tigera.io \"apiserver\": the object has been modified; please apply your changes to the latest version and try again"}
```

An event from the calico-apiserver namespace which appears related is:
```
11m         Warning   FailedToUpdateEndpoint   endpoints/calico-api                     Failed to update endpoint calico-apiserver/calico-api: Operation cannot be fulfilled on endpoints "calico-api": the object has been modified; please apply your changes to the latest version and try again
```

## Steps to Reproduce (for bugs)
Unfortunately, I'm not sure what a minimal number of steps to reproduce would be. I've provided some environment details below.

1.
2.
3.
4.

## Your Environment

* Operating System and version: Amazon Linux 2 (official EKS AMI v1.19.15-eks-9c63c4)
* Amazon EKS 1.19
* Some other operators in the cluster such as Flux and Kyverno are managing Calico NetworkPolicies and Calico HostEndpoints using the v3 CRDs, and so are hitting the API Server.
* Calico installed with tigera-operator helm chart, tigera-operator-v3.22.0
* Values are 
```
helm get values calico -n tigera-operator
USER-SUPPLIED VALUES:
apiServer:
  enabled: true
calicoctl:
  image: docker.io/calico/ctl
  tag: v3.22.0
certs:
  node:
    cert: null
    commonName: null
    key: null
  typha:
    caBundle: null
    cert: null
    commonName: null
    key: null
imagePullSecrets: {}
installation:
  componentResources:
  - componentName: Node
    resourceRequirements:
      limits:
        cpu: 60m
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 200Mi
  - componentName: KubeControllers
    resourceRequirements:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  - componentName: Typha
    resourceRequirements:
      limits:
        cpu: 100m
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 400Mi
  controlPlaneNodeSelector:
    node-type.services.myco.com: mgmt
  controlPlaneReplicas: 3
  controlPlaneTolerations:
  - effect: NoSchedule
    key: node.services.myco.com
    operator: Equal
    value: mgmt
  enabled: true
  kubernetesProvider: ""
  typhaAffinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-type.services.myco.com
            operator: In
            values:
            - mgmt
tigeraOperator:
  image: tigera/operator
  registry: quay.io
  version: v1.25.0
```
