### ISSUE TITLE
Support third-party Docker registries in ImageSet

### ISSUE THREAD

**Issue by geekofalltrades** [tigera/operator#1820]
## Expected Behavior

The [ImageSet API](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.ImageSet) should allow full repository/image strings in its [Image](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Image) field, for example as:

```yml
apiVersion: operator.tigera.io/v1
kind: ImageSet
spec:
  images:
    - image: my-custom-repository/calico/node
      digest: abcd1234
```

## Current Behavior

Right now the operator can't accommodate this workflow, as there seems to be no way to tell it to fetch Docker images from registries other than what's hard-coded in the ImageSet implementation.

## Possible Solution

For explicitness' sake, the `Image` type could expand to include a `name` field, and `ImageSet` could require that the slice contain an image for every required named component.

```yml
apiVersion: operator.tigera.io/v1
kind: ImageSet
spec:
  images:
    - name: calico/node
      image: my-custom-repository/calico-node
      digest: abcd1234
```

This would further accommodate custom-named repositories by not tying identity of the component to the name of the Docker repo.

## Context

Where I work, we control our supply chain by validating and sometimes customizing third-party Docker container images and then mirroring them to our private Docker registry. We try to avoid having production environments install software directly from public Docker registries. This blocks us from being able to switch to the operator, which is otherwise attractive.
