### ISSUE TITLE
Operator doesn't Apply nodeGroup for calico-typha deployment

### ISSUE THREAD

**Issue by TechnicalMercenary** [tigera/operator#1959]
## Expected Behavior

In the Installation 'default' I have set the controlPlaneNodeSelector and the controlPlaneTolerations 

```
  controlPlaneNodeSelector:
    example.com/role-id: devops-server
  controlPlaneTolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Equal
    value: devops-server
```

 I would have expected the deployment that was generated by the operator to have these values in its podSpec.  Unfortunately, only the Toleration appears.  The pod for the calico-kube-controllers does have both the nodeSelector and the Toleration.

## Current Behavior

The podSpec snippet from the calico-typha deployment

```
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: calico-typha
      serviceAccountName: calico-typha
      terminationGracePeriodSeconds: 0
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: devops-server
```
## Possible Solution

I would have expected the nodeSelector I provided to be added to the list of deployment container nodeSelectors

## Context

I'm trying to get these auto-generated calico-typha pods to not be scheduled onto our really large and expensive nodes.

## Your Environment

* Calico (typha) operator 1.25.8
* Calico version: 3.22.2
* Orchestrator version (e.g. kubernetes, mesos, rkt): K8s 1.20
* Operating System and version: AWS Linux
* Link to your project (optional):
