### ISSUE TITLE
node clusterrole does have permissions to read secrets.

### ISSUE THREAD

**Issue by georgyo** [tigera/operator#2006]
## Expected Behavior

When configuring a BGPPeer with has a password, I would expect calico-node to be able to read the secretref.

## Current Behavior

Calico-node does not have permission to list or get secrets, and as such it logs spew the following lines:
```
W0610 00:16:46.957663      69 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: failed to list *v1.Secret: secrets "bgp-password" is forbidden: User "system:serviceaccount:calico-system:calico-node" cannot list resource "secrets" in API group "" in the namespace "calico-system"
E0610 00:16:46.957705      69 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.3/tools/cache/reflector.go:167: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "bgp-password" is forbidden: User "system:serviceaccount:calico-system:calico-node" cannot list resource "secrets" in API group "" in the namespace "calico-system"
```

## Possible Solution

Add the ability to clusterrole calcio-node to be able to list and read secrets.

https://github.com/tigera/operator/blob/fc4f3d8f2c6c44ccf6b6b93623972dd2b45db91e/pkg/render/node.go#L282

## Steps to Reproduce (for bugs)

1. Create a BGP Peer like the following: 
``` 
---
apiVersion: projectcalico.org/v3
kind: BGPPeer
metadata:
  name: my-global-peer4
spec:
  peerIP: 169.254.169.254
  asNumber: 64515
  sourceAddress: UseNodeIP
  password:
    secretKeyRef:
      key: password
      name: vultr-bgp-password
```
2. Watch the logs show it fail to be able to read the secret.

## Your Environment

* Operating System and version:
* Link to your project (optional):
