### ISSUE TITLE
[Feature request] Add ability to set `conditions` on `portmap` in CNI config

### ISSUE THREAD

**Issue by TeddyAndrieux** [tigera/operator#2017]
## Expected Behavior

Being able to restrict the `portmap` "listening" IPs

## Current Behavior

Not possible from the CR

## Possible Solution

I would like to be able to tune a bit the `portmap` CNI configuration, especially adding `conditionsV4` (or V6) from the calico CR.

I suggest adding fields in the current Installation CR, something like this

```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  cni:
    portmap:
      conditionsV4:
        - "-d"
        - "10.10.10.10/32,127.0.0.1/32"
```

So the resulting CNI `portmap` plugin configuration looks like this
```json
{
  "type": "portmap",
  "snat": true,
  "capabilities": {
    "portMappings": true
  },
  "conditionsV4": [
    "-d",
    "10.10.10.10/32,127.0.0.1/32"
  ]
}
```

**Comment by prnvkv** [comment]
This is a good feature request. 
Is there any consideration for this?

**Comment by tmjd** [comment]
It does seem like a reasonable request to be able to configure the portmap plugin when it is enabled. Ideally we'd be able to nest the configuration with the `HostPorts` since only when HostPorts is enabled would the configuration make sense.

I'm also not sure if we'd want to expose the [several options](https://www.cni.dev/plugins/current/meta/portmap/) available for the portmap plugin through our API. I'm wondering if it is reasonable to have a text field that the operator would directly add to the portmap configuration.
@prnvkv or @TeddyAndrieux it sounds like the conditions would be useful for you, would you have any use for the other fields? I'm wondering if we need to bother with any of the other fields or if the 2 conditions fields would be enough.

@TeddyAndrieux sorry for no response on this for so long.

**Comment by TeddyAndrieux** [comment]
For my special use case, the 2 conditions would be enough.

To me, I would only add those 2 conditions and if someone needs something else then it would be considered in another feature request no ?

**Comment by prnvkv** [comment]
Works for me too. 
I also had another Question/Request which is in https://github.com/tigera/operator/issues/2515

Thanks !!

**Comment by tmjd** [comment]
I had a chat with a few of the other operator maintainers today and as I mentioned before it would make the most sense to add portmap configuration to the same structure where `hostPorts` are located. Part of the reasoning is that portmap will only be available (with the operator) when using Calico CNI (not for other CNI plugin types).
So something similar to the original suggestion would probably be the correct API  
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    portmap:
      conditionsV4:
        - "-d"
        - "10.10.10.10/32,127.0.0.1/32"
```

I'd be happy to review a PR if anyone wants to submit the changes for this.
