### ISSUE TITLE
Tigera Operator unable to uninstall cleanly

### ISSUE THREAD

**Issue by prikesh-patel** [tigera/operator#2031]
## Expected Behavior

When uninstalling the _Tigera Operator_ helm chart, it should be able to remove all resource and clean itself up. Then we should be able to reinstall _Tigera Operator_ without having to restart the nodes in an EKS cluster.

## Current Behavior

Uninstalling the helm release locally (using `helm delete -n tigera-operator tigera-operator`) allows the chart to be removed successfully. But when reinstalling the same chart, the `tigera-operator` pod (keeps crashing) and no `calico-node` pods get created. The following are logs in the `tigera-operator` container.

```shell
2022/06/20 15:13:44 [INFO] Version: v1.27.5
2022/06/20 15:13:44 [INFO] Go Version: go1.17.9b7
2022/06/20 15:13:44 [INFO] Go OS/Arch: linux/amd64
2022/06/20 15:14:04 [ERROR] Get "https://XXX.gr7.eu-west-1.eks.amazonaws.com:443/api?timeout=32s": dial tcp: lookup 1D36CABDB9FD90B6E9FB961600E4045D.gr7.eu-west-1.eks.amazonaws.com on 10.52.X.X:53: read udp 100.65.X.X:50421->10.52.X.X:53: i/o timeout
```

This breaks all network connectivity in the cluster. Any new images can't be pulled.

When deleting the _Tigera Operator_ helm release through [terraform](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release), the resource is unable to delete and times out. This may be due to this finaliser on the `Installation` resource, which installs calico.

```terraform
finalizers:
  - tigera.io/operator-cleanup
```

This problem has begun occurring on _Tigera Operator_ helm chart [v2.2.0](https://github.com/stevehipwell/helm-charts/releases/tag/tigera-operator-2.2.0) (_Tigera_ image [v1.27.0](https://github.com/tigera/operator/releases/tag/v1.27.0)  & _Calico_ image [v3.23.0](https://github.com/projectcalico/calico/releases/tag/v3.23.0)).

## Possible Solution

A temporary workaround is to restart the nodes. The `calico-node` pods then begin running on these new nodes, and the `tigera-operator` pod starts running without any restarts.

## Steps to Reproduce (for bugs)

1. Install chart using command `helm install tigera-operator stevehipwell/tigera-operator -n tigera-operator --version 2.2.4 --values tigera-values.yaml`. The following values can be used

```yaml
dnsPolicy: Default
env:
  - name: KUBERNETES_SERVICE_HOST
    value: XXX.gr7.eu-west-1.eks.amazonaws.com
  - name: KUBERNETES_SERVICE_PORT
    value: "443"
hostNetwork: false
installation:
  enabled: true
  spec:
    cni:
      type: AmazonVPC
    componentResources:
      - componentName: Node
        resourceRequirements:
          limits:
            cpu: 1000m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 256Mi
      - componentName: Typha
        resourceRequirements:
          limits:
            cpu: 1000m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 128Mi
      - componentName: KubeControllers
        resourceRequirements:
          limits:
            cpu: 1000m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
    controlPlaneNodeSelector:
      kubernetes.io/os: linux
      lnrs.io/tier: system
    controlPlaneTolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: system
        operator: Exists
    kubernetesProvider: EKS
    nodeMetricsPort: 9091
    nodeUpdateStrategy:
      rollingUpdate:
        maxUnavailable: 25%
      type: RollingUpdate
    registry: quay.io/
    typhaAffinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: lnrs.io/tier
                  operator: In
                  values:
                    - system
    typhaMetricsPort: 9093
    variant: Calico
priorityClassName: ""
rbac:
  create: true
resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 512Mi
serviceAccount:
  create: true
serviceMonitor:
  additionalLabels:
    monitoring-platform: "true"
  enabled: true
tolerations:
  - key: system
    operator: Exists
```

2. Delete chart by running `helm delete -n tigera-operator tigera-operator`.
3. Re-install chart using the same command in step 1.

## Context

We are unable to destroy EKS clusters through terraform, as it times out when uninstalling the _Tigera Operator_ helm release.

## Your Environment

* Operating System and version: Amazon EKS, v1.21.
* Link to your project (optional):

This is possibly related to [projectcalico/calico/issues/6210](https://github.com/projectcalico/calico/issues/6210)
