### ISSUE TITLE
Calico on RKE cluster on Azure not working

### ISSUE THREAD

**Issue by jympetalmd** [tigera/operator#2161]
## Expected Behavior

Was expecting to just follow the documentation and install Calico.
https://projectcalico.docs.tigera.io/getting-started/kubernetes/rancher

## Current Behavior

RKE installation can't continue, calico networking isn't working

## Possible Solution

Seams to be working fine using this addons:
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/addons/calico.yaml

The ippool are 192.168.x.x but seams to work fine!

## Steps to Reproduce (for bugs)

RKE with [addons](https://rancher.com/docs/rke/latest/en/config-options/add-ons/user-defined-add-ons/)
- https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml (CRDs)
- and :
```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 10.42.0.0/16 #Change based on doc (RKE default CIDR)
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
    mtu: 1350 #1450 (default) - trials following lead for Azure
  controlPlaneReplicas: 1
  flexVolumePath: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds #Flatcar requirements
---
...
kind: APIServer 
...
```

## Your Environment

RKE Version: [1.3.13](https://github.com/rancher/rke/releases/tag/v1.3.13)
Flatcar Container Linux - 3033.2.3, please see https://rancher.com/docs/rke/latest/en/os/#flatcar-container-linux
