### ISSUE TITLE
Disabling nodeAddressAutodetectionV6 prevents default ipv6 pool to be created

### ISSUE THREAD

**Issue by simplysoft** [tigera/operator#2255]
We disable `nodeAddressAutodetectionV4` and `nodeAddressAutodetectionV6` in order to configure the node addresses manually. This works as expected for ipv4, but when disabling ipv6 autodetection, the cluster can not be initialized properly, even though IPv4 and IPv6 addresses are configured on each node. 

## Expected Behavior

If we disable `nodeAddressAutodetectionV6` we expect the operator to create the `default-ipv6-ippool`

## Current Behavior

If `nodeAddressAutodetectionV6: {}` is added in installation CRD, the `default-ipv6-ippool` is not created, which in turn causes failure in CNI because no ipv6 addresses can be assigned to nodes / pods. 

## Steps to Reproduce (for bugs)

1. Setup using 
```
calicoNetwork:
    ipPools:
      - blockSize: 26
        cidr: 10.244.0.0/12
        [...]
      - blockSize: 122
        cidr: fd00::/64
        [...]
    nodeAddressAutodetectionV4: {}
    nodeAddressAutodetectionV6: {}
```
2. Check after setup that no `default-ipv6-ippool` is present
4. Change to `nodeAddressAutodetectionV6: ` (to use first found default), wait for operator to process
5. `default-ipv6-ippool` is getting created

## Your Environment
Using chart to install tigera operator (version v3.24.3)
