### ISSUE TITLE
How to set resource requests for DaemonSets & Deployments the Tigera Operator creates

### ISSUE THREAD

**Issue by tomsucho** [tigera/operator#2322]
## Expected Behavior
All components created by Tigera Operator like DaemonSets and Deployments should have resource requests set.

## Current Behavior
None of the components created by Tigera Operator like DaemonSets and Deployments have resource requests set.

## Possible Solution
Could be exposed via Helm chart values file.

## Your Environment: 
EKS, Helm chart: v3.24.1

* Operating System and version:
* Link to your project (optional):

**Comment by tmjd** [comment]
What have you tried and what components are you unable to set? The operator Installation resource is exposed through the helm chart values file. Have you reviewed the [Installation reference](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Installation) because it has exposed the ability to set resources for calico-node, calico-kube-controllers, and calico-typha.

**Comment by tomsucho** [comment]
ahh sorry I was totally unaware of that, I just followed steps from this AWS doc to not break anything on EKS: https://docs.aws.amazon.com/eks/latest/userguide/calico.html
and so it was all installed on defaults. That said defaults should include some base level resource requests?

**Comment by tmjd** [comment]
> That said defaults should include some base level resource requests?

Perhaps it would make sense to put some minimum request on our pods. I don't think we would want to go higher than a minimum or else it is likely to cause issues for those upgrading clusters with very low resources (or low available resources). It is also difficult because the CPU allocated also depends on the actual CPU in the hosts, half of a raspberry pi core can't do  what a half of a high power server core can do for example.

**Comment by tomsucho** [comment]
@tmjd not having anything tho also could lead to issues, as if people put too much on their raspberry pi and there's CPU contention, then Calico pods would get starved without any requests set and so it could lead to some nondeterministic behaviour? Maybe some very minimal resource requests then by default, just to hint folks where it can be set also in yaml, and then have recommended requests for production servers on the documentation website?

**Comment by tomsucho** [comment]
@tmjd would have some examples how the resource requests could be configured for all daemonsets through the install cr? I find it extremly hard to figure this out based on the tables of tables of settings in the docs.
Many thanks!

**Comment by Constantin07** [comment]
@tomsucho here is an example of values file passed to official Helm chart if it helps.
Feel free to add the missing limits.

```yaml
---
installation:
  variant: Calico
  cni:
    type: AmazonVPC
  calicoNetwork:
    linuxDataplane: BPF
  kubernetesProvider: EKS
  # Sensible defaults. Limits can be added when baseline is known.
  calicoNodeDaemonSet:
    spec:
      template:
        spec:
          containers:
            - name: calico-node
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m
  calicoKubeControllersDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-kube-controllers
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m
  typhaDeployment:
    spec:
      template:
        spec:
          containers:
            - name: calico-typha
              resources:
                requests:
                  memory: 64Mi
                  cpu: 40m
  controlPlaneNodeSelector:
    kubernetes.io/os: linux
```
