### ISSUE TITLE
Unable to create tigera-operator with K3s and PodSecurityPolicy enabled

### ISSUE THREAD

**Issue by afarresg** [tigera/operator#2453]
Hello,

We programmatically create K3s clusters, and we are moving from Flannel to Calico. After creating the resources in tigera-operator.yaml and other custom-resources.yaml, the tigera-operator pod doesn't come up. Looking at the K3s journal closely, the following comes up:

```
Error creating: pods \"tigera-operator-65d6bf4d4f-\" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

We had already attempted to move to Calico a year ago, and as part of the tigera-operator.yaml the PodSecurityPolicy object was defined in it:

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: tigera-operator
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "*"
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - "hostPath"
    - "configMap"
    - "emptyDir"
    - "projected"
    - "secret"
    - "downwardAPI"
    # Assume that persistentVolumes set up by the cluster admin are safe to use.
    - "persistentVolumeClaim"
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: "MustRunAsNonRoot"
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "MustRunAs"
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: "MustRunAs"
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
```

This doesn't seem to exist in the current tigera-operator.yaml; however, looking at the source code it seems the PSP's are defined in Go. Applying the aforementioned PSP's manually successfully brings up the tigera-operator pod.

Is there something we are doing wrong? I'm guessing the move to Go has something to do with the fact that K8s >= 1.25 no longer comes with PSP's (which we are planning to move off of in the near future).

## Expected Behavior
Applying the tigera-operator.yaml and custom-resources.yaml files without any additional steps brings up the tigera-operator pod.

## Current Behavior
The tigera-operator pod doesn't come up due to missing PSPs

## Possible Solution
Apply the PSPs that existed in the tigera-operator.yaml file a year ago or so.

## Steps to Reproduce (for bugs)
1. kubectl create -f tigera-operator.yaml
2. kubectl create -f custom-resources.yaml
3. tigera-operator doesn't come up

## Context
We deploy the cluster programmatically, so we need to have a way to easily automate this. The current workaround is to apply the PSP's automatically, but we don't know if that is the correct solution.

## Your Environment
K3s 1.24.6 with Calico 3.25 and Tigera Operator 1.29.0
