### ISSUE TITLE
Tigera operator violates PodSecurity "baseline:latest"

### ISSUE THREAD

**Issue by penoux** [tigera/operator#2996]
When deploying the operator on a K8S 1.25+ cluster with manifests and default PSA on the cluster as `baseline` for new namespaces, the deployment fails.

## Expected Behavior

The installation procedure should succeed without errors.

## Current Behavior

the `tigera-operator` namespace does not have any Pod Security Admission labels set. The deployment fails with the below error

```bash
pods "tigera-operator-6d8c69f9c6-wl988" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostNetwork=true), hostPath volumes (volume "var-lib-calico")
```

## Possible Solution

Set labels explicitely on `tigera-operator` namespace manifest, e.g.

The manifests should set explicitely PSA labels onto the namespace resource, e.g:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tigera-operator
  labels:
    name: tigera-operator
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
```

## Steps to Reproduce (for bugs)

Follow the [operator installation procedure](https://docs.tigera.io/calico/latest/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico) with manifests on a K8S 1.25+ cluster with PSA set to `baseline` as default.

## Your Environment

K8S 1.25.6, PSA activated, set as `baseline` by default when no labels are explicitely set on namespaces.
