### ISSUE TITLE
Calico APIServer does not find certs secret

### ISSUE THREAD

**Issue by framctr** [tigera/operator#3192]
## Expected Behavior
When installing Calico through the `tigera-operator` on k3s and Fedora CoreOS the API Server is correctly started.

## Current Behavior
Calico APIServer cannot start because the pods cannot find the secret `calico-apiserver-certs`:
```
10m         Normal    Scheduled           pod/calico-apiserver-6b895bd67d-86xss    Successfully assigned calico-apiserver/calico-apiserver-6b895bd67d-86xss to node-00
10m         Warning   FailedMount         pod/calico-apiserver-6b895bd67d-86xss    MountVolume.SetUp failed for volume "calico-apiserver-certs" : failed to sync secret cache: timed out waiting for the condition
9m31s       Warning   FailedMount         pod/calico-apiserver-6b895bd67d-86xss    MountVolume.SetUp failed for volume "calico-apiserver-certs" : secret "calico-apiserver-certs" not found
8m33s       Warning   FailedMount         pod/calico-apiserver-6b895bd67d-86xss    Unable to attach or mount volumes: unmounted volumes=[calico-apiserver-certs], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
```

## Possible Solution
`-`

## Steps to Reproduce (for bugs)
Create the `/var/lib/kubelet/volumeplugins/nodeagent~uds` directory to make calico work on Fedora CoreOS (see [GitHib calico issue](https://github.com/projectcalico/calico/issues/2712#issuecomment-510044213))

Install `tigera-operator` through Helm chart with the following values:
```
installation:
  enabled: true
  flexVolumePath: /var/lib/kubelet/volumeplugins
  cni:
    type: Calico
  calicoNetwork:
    mtu: 1400
    bgp: Disabled
    ipPools:
      - blockSize: 26
        cidr: "10.42.0.0/16"
        encapsulation: VXLANCrossSubnet
        disableBGPExport: true
        natOutgoing: Enabled
        nodeSelector: all()
apiServer:
  enabled: true
```

## Context
The installation fails through Terraform.

## Your Environment
* Operating System and version: Fedora CoreOS 39 with `k3s-selinux` installed
* Kubernetes distribution: k3s (v1.27.9+k3s1)

k3s additional args: 
```
      "--selinux",
      "--disable-cloud-controller --disable=servicelb --kubelet-arg='cloud-provider=external'",
      # disable default CNI
      "--flannel-backend=none --disable-network-policy",
      # disable default Traefik Ingress controller
      "--disable=traefik",
      # CIDR to use for pod IPs
      "--cluster-cidr='10.42.0.0/16'",
      # CIDR to use for service IPs
      "--service-cidr='10.43.0.0/16'",
      # Cluster domain
      "--cluster-domain=custom.domain.local",
      # encrypt secrets at rest
      "--secrets-encryption"
```
