### ISSUE TITLE
strict decoding error: unknown field "spec.FailsafeInboundHostPorts"

### ISSUE THREAD

**Issue by JonasJasas** [tigera/operator#3345]
`FelixConfiguration` fails to apply using `calico-operator`. Setting `FailsafeInboundHostPorts` gets rejected.

calico.yaml
```
apiVersion: projectcalico.org/v3
kind: FelixConfiguration
metadata:
  name: default
spec:
  bpfLogLevel: ""
  ipipEnabled: true
  logSeverityScreen: Info
  reportingInterval: 0s
  FailsafeInboundHostPorts: []
```

```sh
kubectl apply -f calico.yaml

globalnetworkpolicy.projectcalico.org/allow-outbound-external configured
The request is invalid: patch: Invalid value: "map[metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"projectcalico.org/v3\",\"kind\":\"FelixConfiguration\",\"metadata\":{\"annotations\":{},\"name\":\"default\"},\"spec\":{\"FailsafeInboundHostPorts\":[],\"bpfLogLevel\":\"\",\"ipipEnabled\":true,\"logSeverityScreen\":\"Info\",\"reportingInterval\":\"0s\"}}\n]] spec:map[FailsafeInboundHostPorts:[]]]": strict decoding error: unknown field "spec.FailsafeInboundHostPorts"
```

Using the same configuration with the `calicoctl` applies without an error and works as expected.
```
./calicoctl apply -f calico.yaml
```

Using Calico v3.27.3 on self hosted Kubernetes v1.28.8, Debian 11
