### ISSUE TITLE
bug: Calico Uninstallation Fails Due to Finalizers on Service Accounts 

### ISSUE THREAD

**Issue by aydosman** [tigera/operator#3413]
## Expected Behavior

The Calico components should be successfully removed/uninstalled without any manual intervention.

## Current Behavior

When attempting to remove Calico via removing the default installation object, the process is unsuccessful due to the presence of finalizers on the service accounts, this also stops the namespace from being terminated successfully. 

## Manual Solution

Manually remove the finalizers on the calico-cni-plugin and calico-node service accounts to allow the removal process to complete.

```bah
kubectl patch serviceaccount calico-cni-plugin -p '{"metadata":{"finalizers":[]}}'
kubectl patch serviceaccount calico-node -p '{"metadata":{"finalizers":[]}}'
```

## Steps to Reproduce

1. Install Calico on an AWS EKS cluster using the provided installation configuration.
2. Attempt to remove Calico via the default installation object.
3. Observe that the removal process does not complete successfully.
4. Check the finalizers on the calico-cni-plugin and calico-node service accounts.

## Environment

Tigera version: v1.34.1
Operating System and version: Amazon Linux 2, Amazon Linux 2023 and Bottlerocket OS
Kubernetes Provider: AWS EKS

Installation Object (some items _removed_):
```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  finalizers:
    - foregroundDeletion
  generation: 3
  labels:
  name: default
spec:
  calicoKubeControllersDeployment:
    metadata:
      labels:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      k8s-app: calico-kube-controllers
                  topologyKey: topology.kubernetes.io/zone
          containers:
            - name: calico-kube-controllers
              resources:
                limits:
                  cpu: 1000m
                  memory: 64Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
  calicoNetwork:
    bgp: Disabled
    linuxDataplane: Iptables
    windowsDataplane: Disabled
  calicoNodeDaemonSet:
    metadata:
      labels:
    spec:
      template:
        spec:
          containers:
            - name: calico-node
              resources:
                limits:
                  cpu: 1000m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 256Mi
          nodeSelector:
            kubernetes.io/os: linux
  cni:
    ipam:
      type: AmazonVPC
    type: AmazonVPC
  controlPlaneNodeSelector:
    kubernetes.io/os: linux
  controlPlaneReplicas: 2
  controlPlaneTolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: system
      operator: Exists
  fipsMode: Disabled
  flexVolumePath: None
  kubeletVolumePluginPath: None
  kubernetesProvider: EKS
  nodeMetricsPort: 9091
  nodeUpdateStrategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate
  nonPrivileged: Disabled
  registry: quay.io/
  typhaDeployment:
    metadata:
      labels:
    spec:
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      k8s-app: calico-typha
                  topologyKey: topology.kubernetes.io/zone
          containers:
            - name: calico-typha
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 10m
                  memory: 128Mi
  typhaMetricsPort: 9093
  variant: Calico
```

Can provide more information if required.
