### ISSUE TITLE
If "KUBERNETES_SERVICE_HOST" is domain, initial installation is not possible. (calico for windows)

### ISSUE THREAD

**Issue by moonek** [tigera/operator#3615]
In an environment where tigera-operator is being installed for the first time considering the use of Windows, if `KUBERNETES_SERVICE_HOST` is a domain, the operator does not work properly.

```
kubectl apply -f - << EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubernetes-services-endpoint
  namespace: tigera-operator
data:
  KUBERNETES_SERVICE_HOST: myk8s.api-endpoint.com # example
  KUBERNETES_SERVICE_PORT: 6443
EOF
```

In the initial k8s environment, `coredns` is not run before tigera-operator installs calico-cni.
Because the `dnsPolicy` of tigera-operator deployment is set to `ClusterFirstWithHostNet`, the above domain cannot be lookup.
Therefore, an error occurs in tigera-operator and calico-cni is not installed.

## Expected Behavior

If `KUBERNETES_SERVICE_HOST` is a domain, an initial install must also be done.

## Current Behavior

A domain lookup failure error continues to occur in the tigera-operator pod.

## Possible Solution

If change tigera-operator's `dnsPolicy` to `Default`, it will not lookup coredns first, but will normally lookup the apiserver address from the dns nameserver set in the host.
After making this change, calico-cni was installed normally, but I am not sure if this is the correct method.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Operating System and version: tigera-operator:v1.34.5
* Link to your project (optional):
