### ISSUE TITLE
Using the operator with Windows enabled by default results in controller crashes and restarts before stabalizing

### ISSUE THREAD

**Issue by jsturtevant** [tigera/operator#3850]
When installing the operator from scratch with windows enabled the controller will startup and crash 2-3 times before everything is setup properly.  It stabilizes after that and everything installs properly.

With an installation like:

```
    installation:
      cni:
        type: Calico
      calicoNetwork:
        bgp: Disabled
        windowsDataplane: HNS
        mtu: 1350
        ipPools:
        - cidr: <cidr>
          encapsulation: VXLAN{{end}}
      serviceCIDRs: 
        - 10.96.0.0/12 # must match cluster service CIDR (this is the default)
     # when kubernetesServiceEndpoint need to pass dns to look up the name properly*
    dnsConfig: 
      nameservers:
        - 127.0.0.53
      options:
        - name: edns0
        - name: trust-ad
    kubernetesServiceEndpoint:
      host: "{{ .Cluster.spec.controlPlaneEndpoint.host }}"
      port: "{{ .Cluster.spec.controlPlaneEndpoint.port }}"
```

*This does require https://github.com/projectcalico/calico/pull/10117 or something similar to enable the dns when serviceendpoint is set.

Results in the restarts and following error before stabalizing:

```
 k get pods -n tigera-operator
NAME                              READY   STATUS    RESTARTS        AGE
tigera-operator-55845b5c8-hjbw2   1/1     Running   4 (4h20m ago)   4h22m
```

```
{"level":"info","ts":"2025-04-01T15:01:50Z","msg":"Starting Controller","controller":"csr-controller"}
{"level":"info","ts":"2025-04-01T15:01:51Z","msg":"Starting workers","controller":"tigera-ippool-controller","worker count":1}
{"level":"error","ts":"2025-04-01T15:01:51Z","logger":"controller_ippool","msg":"Waiting for Installation defaulting to occur","Request.Namespace":"","Request.Name":"default","reason":"ResourceNotReady","stacktrace":"github.com/tigera/operator/pkg/controller/status.(*statusManager).SetDegraded\n\t/go/src/github.com/tigera/operator/pkg/controller/status/status.go:356\ngithub.com/tigera/operator/pkg/controller/ippool.(*Reconciler).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/ippool/pool_controller.go:180\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:118\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:314\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:226"}
{"level":"info","ts":"2025-04-01T15:01:51Z","msg":"Starting workers","controller":"tigera-installation-controller","worker count":1}
{"level":"info","ts":"2025-04-01T15:01:51Z","logger":"controller_installation","msg":"Reconciling Installation.operator.tigera.io","Request.Namespace":"","Request.Name":"default"}
{"level":"info","ts":"2025-04-01T15:01:51Z","msg":"Starting workers","controller":"tigera-windows-controller","worker count":1}
{"level":"info","ts":"2025-04-01T15:01:51Z","msg":"Starting workers","controller":"csr-controller","worker count":1}
{"level":"info","ts":"2025-04-01T15:01:51Z","logger":"controller_csr","msg":"Reconciling CSR Controller","Request.Namespace":"","Request.Name":"default"}
{"level":"info","ts":"2025-04-01T15:01:51Z","logger":"controller_windows","msg":"Reconciling Installation.operator.tigera.io","Request.Namespace":"","Request.Name":"default"}
{"level":"info","ts":"2025-04-01T15:01:51Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"tigera-windows-controller","object":{"name":"default"},"namespace":"","name":"default","reconcileID":"074fabae-4637-4502-b46e-e8e0e1832520"}
{"level":"info","ts":"2025-04-01T15:01:51Z","msg":"Starting workers","controller":"apiserver-controller","worker count":1}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1d66657]

goroutine 624 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:115 +0x1da
panic({0x2249420?, 0x4085bb0?})
        /usr/local/go/src/runtime/panic.go:785 +0x132
github.com/tigera/operator/pkg/controller/installation.validateCustomResource(0xc000a05208)
        /go/src/github.com/tigera/operator/pkg/controller/installation/validation.go:50 +0x277
github.com/tigera/operator/pkg/controller/installation.(*ReconcileWindows).Reconcile(0xc00031d420, {0x2d6d658, 0xc00047bc80}, {{{0x0?, 0x0?}, {0xc00036c136?, 0xc00047bc80?}}})
        /go/src/github.com/tigera/operator/pkg/controller/installation/windows_controller.go:260 +0x41d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2d6d658?, {0x2d6d658?, 0xc00047bc80?}, {{{0x0?, 0x20f3480?}, {0xc00036c136?, 0xc000789800?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:118 +0xa5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000919e00, {0x2d6d690, 0xc0007cd9a0}, {0x2334700, 0xc000a89880})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:314 +0x325
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000919e00, {0x2d6d690, 0xc0007cd9a0})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:265 +0x19d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:226 +0x73
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 257
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.3/pkg/internal/controller/controller.go:222 +0x50c
```
