### ISSUE TITLE
Namespace deletes very slow on eks 1.32 with Calico 3.30.0

### ISSUE THREAD

**Issue by devops-cafex** [tigera/operator#3948]
Deleting any namespace within an EKS 1.32 cluster with Calico 3.30.0 is very slow taking hours to complete, this was not a problem on eks 1.31 and if we downgrade to Calico 3.29.3 again we see no issue

For now we have downgraded to 3.29.3 and everything on several of our clusters operates normally

**Comment by devops-cafex** [comment]
We have the following disabled in our values, if this is of any relevance 

```
goldmane:
  enabled: false
whisker:
  enabled: false 
```
